version: '3'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/tempData/
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./pg_data:/var/lib/postgresql/data
